name: SQL Linter
on:
  push:
    branches: main
jobs:
  SqlLinter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code in Repo
        uses: "actions/checkout@v3"
      - name: Start SQL Linter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect postgres --exclude-rules L039,L016,L014,L009,L004,L010